<script lang="ts">
	import { base } from '$app/paths';
	import { page } from '$app/state';
	import theme from '$generated/theme.json';
	import { onMount } from 'svelte';
	import '../app.css';
	import type { LayoutData } from './$types';

	let { data, children }: { data: LayoutData; children: import('svelte').Snippet } = $props();

	// The manifest is linked from app.html, which is the only markup that survives without
	// JavaScript; nothing renders on a server, so a <svelte:head> link would arrive too late.
	// The service worker registers itself here instead — vite-plugin-pwa injects nothing,
	// because SvelteKit does not run app.html through the html plugin.
	onMount(async () => {
		const { registerSW } = await import('virtual:pwa-register');
		registerSW({ immediate: true });
	});

	const here = $derived(page.url.pathname.replace(/\/$/, ''));
	const section = $derived(
		here === `${base}` || here === '' ? 'home' : here.startsWith(`${base}/icons`) ? 'icons' : 'collections'
	);

	const shipped = $derived(data.index.fonts);
</script>

<svelte:head>
	<meta
		name="description"
		content="Illustrated cover images for komoot collections — drawn from the GPX exports of the tours."
	/>
	<meta name="theme-color" content={theme.paper} />
</svelte:head>

<nav>
	<div class="wrap">
		<ul>
			<li><a href="{base}/" aria-current={section === 'home' ? 'page' : undefined}>Home</a></li>
			<li>
				<a
					href="{base}/collections/"
					aria-current={section === 'collections' ? 'page' : undefined}>Collections</a
				>
				<ul>
					{#each data.index.collections as c (c.slug)}
						<li><a href="{base}/collections/{c.slug}/">{c.name}</a></li>
					{/each}
				</ul>
			</li>
			<li><a href="{base}/icons/" aria-current={section === 'icons' ? 'page' : undefined}>Icons</a></li>
		</ul>
	</div>
</nav>

<div class="wrap">
	{@render children()}

	<footer>
		Generated by <a href="https://github.com/{__REPO__}">{__REPO__}</a>{__BUILT__
			? ` — built: ${__BUILT__}`
			: ''}.
		{#if shipped.length}
			Set in Lora and Poppins, under the
			<a href="{base}/fonts/{shipped[0].licence}">SIL Open Font License</a>.
		{/if}
	</footer>
</div>
